name: Autofix

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write

jobs:
  format:
    name: Auto-format
    runs-on: ubuntu-latest
    if: github.actor == 'aikido-security[bot]' || github.actor == 'aikido[bot]'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: 'style: auto-format aikido security PR'
